### PR TITLE
[Fix] init state now only run on first mount

### LINKED ISSUE #22: Init useEffect run twice on created componnent

### PR DESCRIPTION
**Pull request by wood-crafter**

### CODE REVIEW

**Comment by hoangph271** [comment]
@wood-crafter create a new hook called `useOnMountEffect()` for this logic...?

**Comment by wood-crafter** [comment]
> @wood-crafter create a new hook called `useOnMountEffect()` for this logic...?

Okay, i will work on it

**Comment by wood-crafter** [comment]
@hoangph271 
Please review my newest changes

File: src/views/home/index.js [hunk 1]
```diff
@@ -4,23 +4,24 @@ import { AuthContext } from '../../providers/use-auth'
...
-    Promise.all([getDog(), getDog(), getDog()])
-      .then(dogs => {
-        const [leftDog, midDog, rightDog] = dogs.map(dog => dog.message)
-  
-        setLeft(leftDog)
-        setMid(midDog)
-        setRight(rightDog)
-      })
-  }, [])
+    if (!isFirstMount.current) {
```
Comment (hoangph271) [inline src/views/home/index.js]: @wood-crafter why don't we run this logic in the first mount...?

I don't understand this part:

```jsx
if (!isFirstMount.current) {
```

**Review by hoangph271 — CHANGES_REQUESTED** [review]

File: src/views/home/index.js (hunk 1 above)
Comment (wood-crafter) [reply src/views/home/index.js]: @hoangph271 
dogs was empty on first mount because useInitDog() was not completed push new url.
Im letting useEffect run on second time to prevent image reload and also not be blank

Comment (hoangph271) [reply src/views/home/index.js]: Btw, handle the case where `dogs` is empty...?

Comment (wood-crafter) [reply src/views/home/index.js]: When dogs empty, useEffect just doin nothing, which mean defaul src './demo-main-pic.jpg' that i set will be show

Comment (hoangph271) [reply src/views/home/index.js]: I mean this:

```jsx
  useEffect(() => {
    if (!dogs.length) return

    if (!isFirstMount.current) {
      console.info('!')
      setLeft(dogs[0])
      setMid(dogs[1])
      setRight(dogs[2])
    }
  }, [isFirstMount, dogs])
```

Comment (hoangph271) [reply src/views/home/index.js]: @wood-crafter

Comment (wood-crafter) [reply src/views/home/index.js]: Why do we need this? @hoangph271

Comment (wood-crafter) [reply src/views/home/index.js]: Btw, if we handled case dogs empty, do we still need to check isFirstMount anymore?
@hoangph271

Comment (hoangph271) [reply src/views/home/index.js]: @wood-crafter if the `dogs` is empty, these lines:
```js
setLeft(dogs[0])
setMid(dogs[1])
setRight(dogs[2])
```
Will change the dog values to `undefined`, and cause another (unnecessary) render

Comment (hoangph271) [reply src/views/home/index.js]: @wood-crafter try this out...!

```jsx
useEffect(() => {
  if (dogs.length) {
    setLeft(dogs[0])
    setMid(dogs[1])
    setRight(dogs[2])
  }
}, [dogs])
```

Comment (wood-crafter) [reply src/views/home/index.js]: @hoangph271 
i think that way too, but the useEffect still run 2 times, i dont know why! And im not sure if im doing all this the right way, please point me out

Comment (hoangph271) [reply src/views/home/index.js]: Follow these steps:
- [x] Try my code to see if it works how you want it to...?
- [x] If it works, maybe you don't need `useFirstMount()` for this case
- [x] Don't care if `useEffect` run twice, as long as you don't do anything `unnecessary`, you're fine

Comment (hoangph271) [reply src/views/home/index.js]: @wood-crafter how was it...?

Comment (wood-crafter) [reply src/views/home/index.js]: @hoangph271 
It having bugs that the image have reload with different url.
I tried, but not found out why yet, i will work on it tonight

Comment (hoangph271) [reply src/views/home/index.js]: @wood-crafter maybe finish [this one](https://github.com/wood-crafter/my-tinder/pull/32) first, easy and simple...?

Comment (wood-crafter) [reply src/views/home/index.js]: > @wood-crafter maybe finish [this one](https://github.com/wood-crafter/my-tinder/pull/32) first, easy and simple...?

Will work on both

Comment (wood-crafter) [reply src/views/home/index.js]: @hoangph271  
Please review my newest changes

**Comment by hoangph271** [comment]
@wood-crafter please use our state-of-the-art `useFirstMount()` here:

image

**Comment by hoangph271** [comment]
@wood-crafter #LGTM
